### ISSUE TITLE
Pull Request #8 - v1.1 continua incompatível com Laravel 5.5.

### ISSUE THREAD

**Issue by setefocos** [geekcom/validator-docs#10]
O Pull Request #8 que resolve a incompatibilidade com o Laravel 5.5 se encontra somente no branch Master.  Quando rodamos 

composer require geekcom/validator-docs

Ele retorna a versão 1.1, que continua com o mesmo problema. Poderia corrigir, @geekcom?

Obrigado pelo validador e pela atenção!

**Comment by geekcom** [comment]
@setefocos criei uma nova release, confira ai por favor se está ok...

**Comment by setefocos** [comment]
Show! Obrigado!
