### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by JoaoRuani** [geekcom/validator-docs#109]
Tem alguma limitação para atualizar o composer.json para também suportar php 8?

**Comment by geekcom** [comment]
Vamos precisar verificar no Laravel, pois a lib é pra Laravel, embora dê pra usar fora do framework.

**Comment by leidison** [comment]
Hoje migrei o meu projeto para a versão 8 e deu problema de compatibilidade. Aguardo ansioso pelo suporte, acho o pacote muito completo.

xD

**Comment by imfarias** [comment]
Aguardando atualização da lib

**Comment by solano-catskillet** [comment]
Uma atualização para Laravel 8/ PHP 8 seria muito bom!

**Comment by solano-catskillet** [comment]
Consegui instalar com `composer require geekcom/validator-docs --ignore-platform-reqs`. 
Por enquanto dá para usar assim.

**Comment by geekcom** [comment]
> Uma atualização para Laravel 8/ PHP 8 seria muito bom!

A lib já tem suporte pra Laravel 8, o que acontece é que o Laravel 8 ainda não tem suporte pro PHP8.

**Comment by solano-catskillet** [comment]
@geekcom vc tem certeza? Quando crio um projeto novo com `laravel new test` o composer.json fica assim:
```
...
    "require": {
            "php": "^7.3|^8.0",
...
```

Tem tbm um [merge](https://github.com/laravel/framework/pull/33388) de outubro com o Laravel que resolve incompatibilidades com o PHP8.

Alias, essa lib é da hora! Muito obrigado!

**Comment by Tagliatti** [comment]
Tem alguma coisa errada com o PR #108?

**Comment by guiiamorim** [comment]
Ansioso também para o suporte ao PHP 8!

**Comment by lauroguedes** [comment]
Previsão para que a lib dê suporte para o laravel 8?

**Comment by vicentimartins** [comment]
> Previsão para que a lib dê suporte para o laravel 8?

@lauroguedes A lib já suporta Laravel 8 sim. Segue firme com o uso!
