### ISSUE TITLE
Não consigo usar novas regras de validação do Laravel 8

### ISSUE THREAD

**Issue by sivierostein** [geekcom/validator-docs#113]
Estou tentando usar a regra prohibited_if (https://laravel.com/docs/8.x/validation#rule-prohibited-if) e também usar as validações de cpf e cnpj do validator-docs.
Porem recebo um erro vindo do validator-docs dizendo que não existe a regra prohibited_if.
O laravel não implementou a regra ou o validator-docs é que não conhece as novas regras da versão 8.x ?
Tem como corrigir isto para continuar usando o validator-docs e também tirar proveito das regras novas ?

**Comment by vicentimartins** [comment]
Olá @sivierostein, tudo bem?

Eu acredito que a implementação do validador foi feita sim, tanto que ele está descrito [aqui](https://laravel.com/docs/8.x/validation#rule-prohibited-if) na documentação.

É possível compartilhar o trecho da sua implementação que utiliza a validação do cpf/cnpj?

Valeu!

**Comment by BMasquio** [comment]
Tenho o mesmo problema, usando o `required_if`

**Comment by vicentimartins** [comment]
@BMasquio consegue mostrar parte de sua implementação e log do erro para eu entender o que está acontecendo?

**Comment by BMasquio** [comment]
@vicentimartins , acabei resolvendo de outra forma e por isso não tenho mais o código.

Coloquei o condicional no próprio código, adicionando 'required' às regras no caso positivo da condição.

**Comment by vicentimartins** [comment]
Ok! Agradeço a contribuição e caso tenha problema com algum outro ponto da lib agradeço se puder reportar.
