### ISSUE TITLE
Method geekcom\ValidatorDocs\Validator::validateFormatoCpfcnpj does not exist.

### ISSUE THREAD

**Issue by guiiamorim** [geekcom/validator-docs#120]
Ao atualizar o pacote para a última versão (3.5.3), não consigo mais utilizar os métodos de formato. Estou utilizando Laravel 8, Livewire e PHP 8.
![image](https://user-images.githubusercontent.com/9733153/126331073-039cf03f-deab-4542-a347-894e87c10868.png)
Esta é uma parte do meu código, se puderem me ajudar ficaria grato.

**Comment by ramonMontanhes** [comment]
@geekcom @vicentimartins por favor, se tiverem um tempinho poderiam ver isso? Eu acho que está ocorrendo com geral.

**Comment by vicentimartins** [comment]
@guiiamorim pelo que pude ver do trecho compartilhado, você precisa usar a validação apenas para o formato do cnpj. Mas havendo a necessidade de utilizar ainda a validação de cpf e cnpj, você precisa substituir o `formato_cpfcnpj` por `formato-cpf-cnpj`, conforme está testado em `geekcom\ValidatorDocs\Tests\TestValidator::formatoDoCpfECnpjNoMesmoAtributo`. Me diz se isso resolveu seu problema para fecharmos essa issue.

**Comment by andersondeoliveiramachado** [comment]
@vicentimartins @guiiamorim , desta forma usando Laravel 8 , Livewire e Versão 3.5 funcionou.

![image](https://user-images.githubusercontent.com/1152426/131853125-e8be513c-090c-4936-a56a-93a3d7c4e6fd.png)

**Comment by geekcom** [comment]
> @guiiamorim pelo que pude ver do trecho compartilhado, você precisa usar a validação apenas para o formato do cnpj. Mas havendo a necessidade de utilizar ainda a validação de cpf e cnpj, você precisa substituir o `formato_cpfcnpj` por `formato-cpf-cnpj`, conforme está testado em `geekcom\ValidatorDocs\Tests\TestValidator::formatoDoCpfECnpjNoMesmoAtributo`. Me diz se isso resolveu seu problema para fecharmos essa issue.

Isso aqui pode ser marcado como resposta.
