### ISSUE TITLE
PHP puro

### ISSUE THREAD

**Issue by jccalbuquerque** [geekcom/validator-docs#123]
Show essa lib! 
É possível usar em PHP puro?
Existe algum equivalente para PHP puro?

**Comment by ramonMontanhes** [comment]
Rapaz, eu nunca tentei, mas acredito que basta inicializar um projeto com o composer pra facilitar, instalar a lib e usar por namespace como qualquer outra, Deve dar ruim se ela fizer uso de algum método específico do Laravel.

**Comment by jccalbuquerque** [comment]
Pois é.
Fiz isso apenas para teste e criei uma pessoa, deu tudo certo.
Não sei mais para frente.
Julio Albuquerque

Em ter., 17 de ago. de 2021 às 14:22, Ramon Carvalho <
***@***.***> escreveu:

**Comment by vicentimartins** [comment]
@jccalbuquerque eu nunca tive a necessidade de usar sem o suporte do Laravel. Seria muito interessante ter algum material de referência (guia, blog post, vídeo, etc) para quem tiver esta necessidade poder usar de guia. Se você fizer algo do tipo, compartilha conosco pra eu referenciar no README. Obrigado pela consideração!
