### ISSUE TITLE
Possibilidade de CPF/CNPJ com zeros

### ISSUE THREAD

**Issue by leacarbonera** [geekcom/validator-docs#124]
Olá, seria possível implementar uma opção onde o CPF/CNPJ (são obrigatórios no BD), pudessem ser passados com 000.000.000-00 por exemplo? Sei que não é o correto, principalmente pq no BD é obrigatório, mas no dia a dia as vezes se faz necessário.

No restante, top demais, parabens.

**Comment by geekcom** [comment]
Oi @leacarbonera, eu não vejo em que ocasião seria necessário cadastrar um CNPJ 000.000.000-00

**Comment by vicentimartins** [comment]
@leacarbonera isso poderia abrir falhas de segurança no pacote. Acho que não faz sentido implementar, e acretido que podemos fechar esta issue.

**Comment by leacarbonera** [comment]
pode sim... sem problemas.
Obrigado pelo retorno

Em qui., 10 de fev. de 2022 às 10:24, Vicente Martins <
***@***.***> escreveu:
