### ISSUE TITLE
[Ajuda] - Testar a lib no Laravel 9.

### ISSUE THREAD

**Issue by geekcom** [geekcom/validator-docs#126]
Olá pessoal, precisamos ajuda para testar a nossa lib em uma instalação nova do [Laravel 9](https://laravel.com/docs/9.x).
Acredito que já estamos atualizados, pois aparentemente não tivemos [mudanças](https://laravel.com/docs/9.x/releases) no framework, assim não teríamos grandes problemas. Entretanto s é necessário realizar testes funcionais para garantir esse ponto.

Esperamos que apareçam pessoas voluntárias afim de ajudar-nos nesta tarefa, muito obrigado pela contribuição de todos, o open source vive graças a vocês. S2

**Comment by me42th** [comment]
Opa, boa noite man! Como faço pra colaborar? O que preciso fazer pra resolver esse ticket?

**Comment by geekcom** [comment]
Oi @me42th, obrigado pela disposição em contribuir com o projeto, basicamente pra realizar testes você vai precisar de uma instalação nova do Laravel 9, instalar a validator-docs e testa os campos de validação, conforme a documentação, tem um exemplo de controller inclusive.

**Comment by omarkdev** [comment]
Hey @geekcom, vou realizar alguns testes e te retorno em alguns dias

**Comment by fuentesbr** [comment]
Olá, estou tendo o mesmo problema para a validação 'cpf': 

`Method Illuminate\Validation\Validator::validateCpf does not exist.`

**Comment by ronaldaraujo** [comment]
> Olá, estou tendo o mesmo problema para a validação 'formato_cpf':
> 
> `Method geekcom\ValidatorDocs\Validator::validateFormatoCpf does not exist.`

O mesmo por aqui...

**Comment by raphael-heilbuth** [comment]
> Olá @geekcom, fiz uma instalação limpa do laravel 9 e tentei utilizar esta lib para validar o formato de cpf e cnpj e recebo a seguinte mensagem de erro ao utilizar o alias 'formato_cpf_cnpj':
> 
> `Method geekcom\ValidatorDocs\Validator::validateFormatoCpfCnpj does not exist.`
> 
> quando utilizo apenas 'cpf_cnpj', a lib funciona normalmente.

Ainda persiste esse problema? Tive o mesmo erro:
geekcom\ValidatorDocs\Validator::validateFormatoCpfCnpj does not exist. {"exception":"[object]

**Comment by geekcom** [comment]
Testado e validado no Laravel 9.
