### ISSUE TITLE
Laravel 5.6

### ISSUE THREAD

**Issue by tatianilima** [geekcom/validator-docs#14]
Bom dia! 

Parabéns pela iniciativa! Ao utilizar o validador para o cpf, mesmo que eu insira um cpf inválido ele permite prosseguir. 

Embora eu tenha colocado a validação do cpf no array de validação
'cpf' => 'required|cpf'

Rodei o composer install tbm e acrescentei geekcom\ValidatorDocs\ValidatorProvider::class,   no app.php

Mesmo assim o cpf inválido não é barrado.. Será que estou esquecendo alguma etapa ou não é compativel com laravel 5.6?

**Comment by Iraecio** [comment]
Estou usando Laravel 5.6 e funcionando perfeitamente.

Valida cpf apenas valido qualquer outro cpf que a soma nao seja 11 da error.

**Comment by geekcom** [comment]
Olá @tatianilima , nos testes funciona em laravel 5 em diante, você pode executar os testes de unidade para conferir melhor

**Comment by geekcom** [comment]
@Iraecio você pode descrever melhor o problema?

**Comment by Iraecio** [comment]
@geekcom  o meu não é um problema, é apenas resposta a pergunta @tatianilima 

"...será que estou esquecendo alguma etapa ou não é compativel com laravel 5.6?"

**Comment by geekcom** [comment]
É compativel com 5.6
