### ISSUE TITLE
Não está funcionando no Laravel 5.7

### ISSUE THREAD

**Issue by jppcel** [geekcom/validator-docs#15]
Bom dia,

O validador não está funcionando no Laravel 5.7, ocorre o seguinte erro: Method Illuminate\Validation\Validator::validateCpf does not exist.

**Comment by kkkasio** [comment]
mesma coisa aqui ! segui o tutorial da instalação. estou usando laravel 5.6

**Comment by geekcom** [comment]
Testado no Laravel 5.7 com sucesso, a lib funciona em qualquer versão 5.x....
