### ISSUE TITLE
Aceitar valor NULL quando a validação não possuir "required"

### ISSUE THREAD

**Issue by andre-novapc** [geekcom/validator-docs#16]
Estou utilizando a validação "cpf_cnpj", porém o meu campo é de preenchimento opcional. Então se tento salvar sem preencher  o CPF ou CNPJ a validação é feita mesmo assim.

Tem como obrigar a validação somente quando for "required|cpf_cnpj" e quando estiver apenas "cpf_cnpj" não validar se o campo não estiver preenchido?

**Comment by Iraecio** [comment]
envia apenas campos preenchidos.

**Comment by andre-novapc** [comment]
Deu certo! Obrigado!
