### ISSUE TITLE
Definir a versão mínima do PHP [Sugestão]

### ISSUE THREAD

**Issue by raphaeldealmeida** [geekcom/validator-docs#18]
O requisito da lib é illuminate/support: 5.*. Sendo o mais baixo 5.0 que requer PHP 5.4.0 [1]. Já o requisito dev é PHPUnit 7.5 que requer PHP 7.1. Sugiro que escolha uma versão para requisito do PHP e coloque no package.json para ajudar o usuário entender o ambiente necessário.

Outra coisa que pode ajudar também é o CI executar os testes em várias versões do PHP.

[1] https://github.com/laravel/framework/blob/5.0/composer.json
[2] https://github.com/sebastianbergmann/phpunit/blob/7.5/composer.json

**Comment by geekcom** [comment]
Muito bem observado, obrigado pela sugestão, vou resolver isso assim que puder.

**Comment by geekcom** [comment]
Resolvido
https://github.com/geekcom/validator-docs/pull/31
