### ISSUE TITLE
Method geekcom\Validator Docs\Validator::validate Required, does not exist

### ISSUE THREAD

**Issue by syond** [geekcom/validator-docs#22]
Fala galera.

Estou utilizando Laravel 5.8 e tentando fazer o `store()` mas tá dando esse erro quando clico em cadastrar.

> Method geekcom\Validator Docs\Validator::validate Required, does not exist

```
ImediataController.php

public function store(ImediataStoreRequest $request)
    {
        $dados = $request->validated();        

        $funcionario_id = Auth::id();

        $dados['funcionario_id']    = $funcionario_id;

        Imediata::create($dados);

        return redirect()->route('acao-imediata.index')->with('success', "Ação Imediata cadastrada com sucesso!");
    }
```

```
ImediataStoreRequest.php

public function rules()
    {
        return [
            'nome'              => 'required,' . $this->imediata,
            'data'              => 'required,' . $this->imediata,
            'descricao'         => 'required,' . $this->imediata,
            'equipamento_id'    => '',
            'funcionario_id'    => 'required,' . $this->imediata,
            'status'            => '',
        ];
    }
```

Alguma solução ?

**Comment by geekcom** [comment]
@syond vc seguiu as instruções de instalação?

**Comment by tiagofrancafernandes** [comment]
Só pra deixar registrado caso alguém passa pelo mesmo problema que eu:
No meu caso estava dando um erro semelhante mas era que eu havia instalado um novo pacote localmente, mas no meu servidor de teste eu não havia executado `composer install` para instalar o que faltava então o Laravel estava procurando no último pacote validador instaladado.
