### ISSUE TITLE
Validação titulo de eleitor

### ISSUE THREAD

**Issue by MrEko** [geekcom/validator-docs#36]
Parece que não funciona com todos os numeros:
007202350108 deu como inválido e foi gerado no http://4devs.com.br/gerador_de_titulo_de_eleitor

Estranhamente na validação do proprio site, dá como inválido.
Nesse outro site:
https://www.treinaweb.com.br/ferramentas-para-desenvolvedores/validar/titulo
Indica como válido

**Comment by MrEko** [comment]
@geekcom Não é CPF, é titulo de eleitor.

Exemplo: 007202350108

**Comment by geekcom** [comment]
Esses exemplos de Titulo de Eleitor não passam nos testes de validação da Validator Docs, nem na validação do [TSE](http://www.tse.jus.br/eleitor/validacao-de-documentos), a validação da lib é bem confiável, existe algo errado com o 4devs.

**Comment by MrEko** [comment]
Tem razão, pelo o que pesquisei aqui, a validação da lib está correta.

O problema está na seguinte exceção:

> Para os títulos emitidos em São Paulo ou Minas Gerais (UF 01 ou 02), o resto 0 no cálculo do 1º ou do 2º DV será assumido como 1.

E o gerador da _4devs_ **não** leva isso em conta.

Talvez por uma observação no readme para alertar desse problema no site indicado.

**Comment by geekcom** [comment]
Ou podemos indicar outro gerador.

**Comment by mariohmol** [comment]
@MrEko eu testei outros 2 algoritmos com esse check de resto = 0 e ambos deram codigo verificador 16.. e nao 08 como vc tem

funcao1:
https://github.com/mariohmol/js-brasil/blob/master/src/create.ts#L223

funcao2: 
https://github.com/mariohmol/js-brasil/blob/master/src/create.ts#L270

os testes:
https://github.com/mariohmol/js-brasil/blob/master/test/validate.ts#L115

**Comment by MrEko** [comment]
@mariohmol sim, já tinha percebido e reportado isso.
O problema está no gerador do site da 4devs.

Vou fechar para não criar confusão, só fica o alerta pra quem usar este gerador, que não é 100% confiável.

**Comment by 4devs-net-br** [comment]
https://4devs.net.br/gerador-cpf
