### ISSUE TITLE
Obrigatoriedade

### ISSUE THREAD

**Issue by ederzadravec** [geekcom/validator-docs#52]
Amigo, ao meu ver, a validação dos campos não deveria obrigar eles a estarem preenchidos.

Por exemplo, meu formulário tem um campo CNPJ que não é obrigatório, ao usar a validação `cnpj`, mesmo que o campo vá vazio, ele da erro no campo dizendo que não é válido.

Para obrigar um campo ser obrigatório, o laravel já tem o `required`

**Comment by geekcom** [comment]
Olá @ederzadravec  o Laravel sempre vai considerar null ou vazio como inválido, para não acontecer isso basta você marcar seu campo como `nullable`, observe o exemplo abaixo:

```
$this->validate($request, [
    'cpf' => 'nullable|cpf',
]);

```
Neste caso estamos informando que o campo cpf não será obrigatório, você pode fazer isso para qualquer tipo de docmento validado pela lib.
