### ISSUE TITLE
Validação de CNH errada

### ISSUE THREAD

**Issue by MrEko** [geekcom/validator-docs#53]
O validador implementado não cobre todos os casos corretamente.
Exemplo real que chegou pra mim hoje: 04463004100.

O validador do **4devs** usado como referência do projeto indica **falso**.
O validador em: 
https://www.treinaweb.com.br/ferramentas-para-desenvolvedores/validar/cnh
Aponta corretamento como **verdadeiro**.

Vou pegar o algoritmo correto com o detran. E depois faço um pull request.

Mas já fica o alerta, e é a 2ª vez que encontro erro nas implementação desse **4devs**. Não são muito confiáveis não.

E acredito que deva ter mais exemplos nos casos de teste, com apenas 1 caso é muito fácil passar um algoritmo problemático.

**Comment by geekcom** [comment]
Boa @MrEko, obrigado pela ajuda que tem dado na lib, realmente os validadores da 4devs tem decepcionado. Vou escrever novos casos de testes para termos maior cobertura.

**Comment by geekcom** [comment]
https://github.com/geekcom/validator-docs/pull/54
