### ISSUE TITLE
Nomes dos atributos

### ISSUE THREAD

**Issue by enniosousa** [geekcom/validator-docs#6]
Olá,

Os nomes dos atributos não estão sendo passados.

No arquivo ```ValidatorProvider.php``` está assim
```
public function boot()
    {

        $me = $this;

        $this->app['validator']->resolver(function ($translator, $data, $rules, $messages) use ($me) {
            $messages += $me->getMessages();
            return new Validator($translator, $data, $rules, $messages);
        });
    }
```

Mas deveria estar assim

```
public function boot()
    {

        $me = $this;

        $this->app['validator']->resolver(function ($translator, $data, $rules, $messages, $attributes) use ($me) {
            $messages += $me->getMessages();

            return new Validator($translator, $data, $rules, $messages, $attributes);
        });
    }
```

**Comment by setefocos** [comment]
Sim. Esse é um problema sério porque faz a função attributes() do Form Request parar de funcionar. Foi só eu instalar esse validador que parou de funcionar. Isso é uma pena pois o validador funciona bem.

**Comment by enniosousa** [comment]
Pelo tempo que reportei esta ocorrência pensei que eles já tinham consertado. Uma pena o repositório estar morto.

**Comment by geekcom** [comment]
Olá @enniosousa você poderia ajudar com esse problema?, essa issue está participado do Hacktoberfest.

**Comment by setefocos** [comment]
#8

**Comment by geekcom** [comment]
Fechado
