### ISSUE TITLE
Validação unique

### ISSUE THREAD

**Issue by extramicro** [geekcom/validator-docs#84]
Como utilizo a validação de cpf unique key?
Tentei assim e não funcionou.
				'cpf'			=> 'required|unique:users,cpf|cpf',

**Comment by bitdev1999** [comment]
'cpf' => 'required|cpf|unique:users'

**Comment by extramicro** [comment]
> 'cpf' => 'required|cpf|unique:users'

Tentei isso também, mas não valida estoura exception.
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xxxxxxxxxxx' for key 'cpf' (SQL: update `users` set `cpf` = xxxxxxxxxxx, `users`.`updated_at` = 2020-06-29 09:22:04 where `id` = 2)

**Comment by geekcom** [comment]
Olá @extramicro, essa issue não está relaciona a lib, você tá tentando essa validação em um método update certo? Faz o seguinte:

```php

use Illuminate\Validation\Rule;

Validator::make($data, [
    'email' => [
        'required',
        Rule::unique('users')->ignore($user->id),
    ],
]);
```

Assim você está ignorando a regra `unique` no update, desta forma essa violação de chave duplicada não acontecerá.

Para mais informações verifique a documentação do Laravel:


**Forcing A Unique Rule To Ignore A Given ID:**

https://laravel.com/docs/7.x/validation#rule-unique

**Comment by extramicro** [comment]
@geekcom é um método update sim, mas eu não quero ignorar, quero utilizar a validação do CPF dessa lib.
