### ISSUE TITLE
Criar validação para qualquer documento Brasileiro que ainda não tem em ValidatorDocs.

### ISSUE THREAD

**Issue by geekcom** [geekcom/validator-docs#87]
A ideia desta issue é que as pessoas possam colaborar com o projeto validator-docs Brasil e criem uma validação para qualquer documento brasileiro que não esteja "coberto" pela lib.

**Comment by mechamobau** [comment]
@geekcom acho interessante utilizar uma biblioteca que tenha este foco e ir migrando aos poucos as validações.
O repositório da biblioteca é https://github.com/VitorLuizC/brazilian-values, é bem leve e fácil de usar :)

**Comment by thicolares** [comment]
@geekcom, vou fazer um PR para Inscrição Estadual

**Comment by thicolares** [comment]
@geekcom, criei um novo issue específico para que o PR não feche este issue genérico:
https://github.com/geekcom/validator-docs/issues/94

**Comment by geekcom** [comment]
Galera, cês são incríveis, muito obrigado por todas as contribuições ate aqui.
