### ISSUE TITLE
Adicionar tópico hacktoberfest

### ISSUE THREAD

**Issue by lhsazevedo** [geekcom/validator-docs#88]
Neste ano, mantenedores de projetos terão que optar por participar do Hacktoberfest adicionando o tópico "hacktoberfest" ao repositório.

Reparei que este repo está na [lista de repositórios PHP brasileiros aceitando contribuições para o #hacktoberfest](https://github.com/PHPRio/hacktoberfest), mas ainda não possui este tópico.

Adicionalmente, o repositório será listado na [página do tópico](https://github.com/topics/hacktoberfest) junto à outros que optaram por participar.

[Mais informações aqui](https://www.youtube.com/watch?v=FxBv4FMcDgo).

**Comment by geekcom** [comment]
Muito obrigado cara, não sabia da mudança, já inclui este repositório.

**Comment by lhsazevedo** [comment]
🚀
