### ISSUE TITLE
Package autodiscovery

### ISSUE THREAD

**Issue by joaomisturini** [geekcom/validator-docs#9]
Olá, estou usando este package em meus projetos e gostaria de saber se o mesmo ainda está sendo mantido.

Em caso afirmativo, gostaria de saber se posso enviar uma PR para adição do package autodiscovery.

Desde já, agradeço!

**Comment by geekcom** [comment]
Sim @joaomisturini a lib é mantida aind, claro que pode toda PR é muito bem vinda.
