### ISSUE TITLE
RG - Registro Geral

### ISSUE THREAD

**Issue by raphaeldealmeida** [geekcom/validator-docs#91]
Verifiquei que não existe validador para RG no projeto.
Realizando uma [pequena busca na internet](https://pt.wikipedia.org/wiki/C%C3%A9dula_de_identidade) constatei que cada Estado tem autonomia para emitir RG com seu padrão.

Seria o caso de criar uma validação para cada Estado ou considerar a menos restritiva?

**Comment by geekcom** [comment]
Acho melhor nesse caso ter uma pra cada estado.
