### ISSUE TITLE
Method Illuminate\Validation\Validator::validateCnpj does not exist

### ISSUE THREAD

**Issue by VagalPHP** [geekcom/validator-docs#92]
Olá,

Estou tentando utilizar o pacote no meu projeto Laravel 7, seguindo exatamente as etapas descritas na documentação, me deparo com este erro quando utilizo a validação. Estou tentando corrigir mas não estou conseguindo encontrar uma solução.

**Comment by geekcom** [comment]
Todos os testes foram executados com sucesso @VagalPHP, vc pode fornecer mais informações? Assim a comunidade pode te ajudar.
